name: web_window_api
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  
dependencies:
  meta: any
  web: any

  pshondation:
    git:
      url: https://github.com/pshonkaaa/package.pshondation.dart.git