name: web_window_api
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: '>=3.1.1 <4.0.0'
  
dependencies:
  meta: any
  js: any

  foundation:
    git:
      url: https://github.com/pshonkaaa/package.foundation.dart.git